version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    command: ./bin/entrypoint.sh
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://test_user:test_password@db:5432/test_db
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

