"""[update][update User Model, user_id instead of id]

Revision ID: 8c6705d0ff4c
Revises: b2b2e78fe1e7
Create Date: 2024-08-11 21:17:26.252838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6705d0ff4c'
down_revision: Union[str, None] = 'b2b2e78fe1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
