"""modificacion de relationships

Revision ID: d72f309c9311
Revises: e156c3d64c46
Create Date: 2024-09-12 12:27:19.637267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72f309c9311'
down_revision: Union[str, None] = 'e156c3d64c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_users_email'), 'users', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_users_user_id'), 'users', ['user_id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_users_username'), 'users', ['username'], unique=True, schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_users_username'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_user_id'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_email'), table_name='users', schema='users')
    op.drop_table('users', schema='users')
    # ### end Alembic commands ###
