"""[ADD][new budget schema models added (budget, cateogryexpenses, expenses, incomes, tackingmonth)]

Revision ID: e156c3d64c46
Revises: 8c6705d0ff4c
Create Date: 2024-08-11 22:00:21.874582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e156c3d64c46'
down_revision: Union[str, None] = '8c6705d0ff4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
